Добавляет вспомогательные функции
htmlacademy-javascript/2086233-kekstagram-simple-27 pull request #2
Opened 2022-10-02 19:27 UTC by Victoria273

Алёна, привет! Функции нашла, изучила и дописала к ним условия, единственное не поняла как бы проверить выполнение кода на деле, что всё в порядке и при передаче аргументов он выполняется, подскажи, пожалуйста

2022-10-03 09:51 UTC, Safyann commented
можно использовать console.log(), и смотреть в браузере через dev tools, это самый простой способ

2022-10-03 13:43 UTC, Victoria273 commented
> можно использовать console.log(), и смотреть в браузере через dev tools, это самый простой способ

Спасибо, Алёна! Ввожу в dev tools в Console, но пока не понимаю как поправить ошибки cо swap и кажется checkLength цифры как строку не воспринимает
![Снимок](https://user-images.githubusercontent.com/103250430/193592525-93461fe7-5437-4032-8aad-4b2518bcbb07.PNG)

2022-10-04 15:57 UTC, Safyann requested changes
Хорошо, но есть несколько моментов, которые надо поправить, ошибки линта и чуть логики в функции рандомного числа

2022-10-04 15:57 UTC, Safyann commented on js/main.js
> +    let swap = firstNumber;
swap нигде не переписывается поэтому лучше объявлять через const

2022-10-04 15:57 UTC, Safyann commented on js/main.js
> +  if (firstNumber >= 0 && secondNumber >= 0 && firstNumber <= secondNumber) {
проверку на отрицательные лучше сразу сделать в начале, например `if (firstNumber < 0 || secondNumber < 0) {
    return NaN;
  }`
тогда не надо прописывать длинное условие и можно избавиться от firstNumber >= 0 && secondNumber >= 0
и еще сейчас все равно функция работает с отрицательными, так как если первый if не пройдет, то второй пройдет, так как там нет проверки на положительные

2022-10-04 15:57 UTC, Safyann commented on js/main.js
> +    string.slice(0, MAX_LENGTH - 1) + '…' : string;
линт ругается, ждет конкатенацию строк, можно здесь посмотреть https://learn.javascript.ru/string#kavychki

2022-10-04 22:07 UTC, Victoria273 commented on js/main.js
> +  if (firstNumber >= 0 && secondNumber >= 0 && firstNumber <= secondNumber) {
Точно, правлю!

2022-10-04 22:07 UTC, Victoria273 commented on js/main.js
> +    let swap = firstNumber;
Спасибо, Алёна! Поправила, я думала, то что мы записываем её потом в secondNumber что-то значит, но понятно - саму-то её мы тут не меняли

2022-10-04 22:48 UTC, Victoria273 commented on js/main.js
> +    string.slice(0, MAX_LENGTH - 1) + '…' : string;
Тут пока никак не пойму даже с теорией(..Понимаю за собой, что пытаюсь определить, где нужны кавычки наугад..
Если слайс пробую заключить в одинарные или обратные - `string.slice(0, MAX_LENGTH - 1)` + '…' : string; - то же самое линт пишет

2022-10-07 08:49 UTC, merged

2022-10-07 08:49 UTC, Safyann approved these changes
Принято, но линт надо будет поправить

2022-10-07 08:49 UTC, Safyann commented on js/main.js
> +    return Math.floor(Math.random() * (secondNumber - firstNumber + 1)) + firstNumber;
14-17 строки тоже самое что и 8-10, можно вынести из if else ниже так как если числа < 0 то вернется NaN и функция дальше не пойдет

2022-10-07 08:49 UTC, Safyann commented on js/main.js
> +  return NaN;
вынести сюда, так как проверка уже идет начале функции

2022-10-07 08:49 UTC, Safyann commented on js/main.js
> +    string.slice(0, MAX_LENGTH - 1) + '…' : string;
![image](https://user-images.githubusercontent.com/29498049/194512611-c64b8cc7-870b-4fc8-9c59-642682f47279.png)

2022-10-07 08:49 UTC, Safyann commented on js/main.js
> +  return NaN;
![image](https://user-images.githubusercontent.com/29498049/194513177-4cd9809a-3994-4000-abe4-0b8f7f2cbf87.png)

2022-10-07 09:59 UTC, Victoria273 commented on js/main.js
> +    return Math.floor(Math.random() * (secondNumber - firstNumber + 1)) + firstNumber;
Спасибо, Алёна! Думала, что должен быть способ сократить, т.к. действие в этих строках повторяется..Вынесла за условие, получается 1. проверка на отрицательные 2. первое число больше второго, меняем местами и далее 3. вычисляем и возвращаем результат.

2022-10-07 10:11 UTC, Victoria273 commented
Поняла, ${string.slice(0, MAX_LENGTH - 1)}… у нас получается произвольное выражение