Модуляция
htmlacademy-javascript/2086233-kekstagram-simple-27 pull request #4
Opened 2022-10-14 13:17 UTC by Victoria273

Алёна, привет! В #3 PR ответила, скопирую сюда. Никак не могу понять как реализовть..казалось бы простенько же. Я определила, что нужна конструкция цикла for (let i = 1, i <= POSTS_COUNT, i++) {index = i} , но не могу её корректно вставить в код функции, выдает ошибки.
const createPost = (index) => ({
for (let i = 1; i <= POSTS_COUNT; i++) {index = i}
id: index,
url: photos/${index}.jpg,
description: DESCRIPTIONS[getRandomInteger(0, DESCRIPTIONS.length - 1)],
likes: getRandomInteger(15, 200),
comments: getRandomInteger(0, 200),
});
Пробовала найти похожее, понять что не так делаю, какая должна быть пунктуация..

---
:mortar_board: [Модуляция](https://up.htmlacademy.ru/javascript/27/user/2086233/tasks/10)

2022-10-14 20:06 UTC, Safyann requested changes

2022-10-14 20:06 UTC, Safyann commented on js/data.js
> +});
ты сначала пробегаешься циклом и делаешь index = i, но последний результат index = 25 а потом идет присваивание в объект, то есть у тебя все время будет выводиться один и тот же объект, тут надо объект в for засунуть и синтаксис чуть поправить 
![code](https://user-images.githubusercontent.com/29498049/195929983-d141d54b-3d1f-4258-abe1-26f0ba692e58.png)

но так как ниже мы уже проходимся по массиву и передаем index в функцию, то тут цикл не нужен
![code](https://user-images.githubusercontent.com/29498049/195931808-92ad5c3e-d49c-4718-b974-6af0cfdced1f.png)

2022-10-14 20:06 UTC, Safyann commented on js/main.js
> +import './utils.js';
можно не экспортировать все файлы, а только то что нужно, как пример ниже `import {postsContent} from './data.js';`
и так как в data.js у тебя есть `import {getRandomInteger} from './utils.js';` то utils.js' тоже экспортируется и подтянется

2022-10-14 20:06 UTC, Safyann commented on js/main.js
> +  postsContent()
postsContent не функция,  а массив постов, не надо вызывать со `()`, просто `postsContent`

2022-10-14 20:06 UTC, Safyann commented on js/utils.js
> +checkLength();
код ругается что ничего не передала, лучше вызывать сразу с аргументами `checkLength('ffsfs ssfsf');` либо вообще убрать вызов, в дальнейшем все равно будем чистить код

2022-10-15 14:07 UTC, Victoria273 commented on js/data.js
> +});
Да, когда добавляю цикл, единица везде вместо индекса, а без него индексы в массиве перебираются, но с нуля до 24..а сюда, в (obj, index) => createPost(index), понимаю никак цикл нам не пристроить

2022-10-19 11:59 UTC, Safyann commented on js/data.js
> +const postsContent = Array.from({length: POSTS_COUNT}, (obj, index) => createPost(index));
так как индекс в программирова

2022-10-19 11:59 UTC, Safyann commented on js/data.js
> +});
так как индекс в программировании с 0 то можно передавать index + 1, то есть (obj, index) => createPost(index + 1), тогда будет от 1 до 25

2022-10-19 12:00 UTC, merged

2022-10-19 12:04 UTC, Victoria273 commented on js/data.js
> +});
Алёна, ведь точно, какое простое решение, а я не догадалась! Спасибо большое!