Module8 task1
htmlacademy-javascript/2086233-kekstagram-simple-27 pull request #6
Opened 2022-10-29 12:49 UTC by Victoria273

Кажется я в обработке подзапуталась, пересматривала скринкасты

2022-10-30 16:42 UTC, Safyann requested changes

2022-10-30 16:42 UTC, Safyann commented on js/utils.js
> +export {getRandomInteger, checkLength, isEscapeKey};
экспортируешь раньше чем объявляешь, так как getRandomInteger и checkLength - объявлены как function, то они всплывают и проблем с ним не было, а isEscapeKey объявила через const, то тут ошибка, так как js еще не знает что это такое, лучше экспортируй всегда в конце файла, а не в начале, чтобы избежать проблем

2022-10-30 16:42 UTC, Safyann commented on js/photos-generation.js
> +  photoPost.children[1].querySelector('.picture__likes').value = postsContent[i].likes; // Присваиваем число лайков и комментов в <span> внутри <p>
я бы убрала .children[1], так как не понятно почему именно 1, лучше сразу поиск

2022-10-30 16:42 UTC, Safyann commented on js/form-popup.js
> +import {isEscapeKey} from './utils';
добавить расширение для utils

2022-10-30 16:42 UTC, Safyann commented on js/main.js
> +import './comment-validation.js';
забыла экспорт form-popup

2022-10-31 08:04 UTC, Victoria273 commented on js/main.js
> +import './comment-validation.js';
Алёна, привет! Спасибо! Всё поправила. Сейчас выбор файла для загрузки открывается, но фото и форма его редактирования пока не загружается, так не должно быть?

2022-11-01 07:49 UTC, Safyann approved these changes
Принято, потерялась ) в коде, поэтому ошибка

2022-11-01 07:49 UTC, Safyann commented on js/form-popup.js
> +}
потрерялась )

2022-11-01 07:49 UTC, merged

2022-11-01 11:11 UTC, Victoria273 commented on js/form-popup.js
> +}
оо, вот как замылилось у меня, спасибо большое, Алёна!