Добавляет модуль масштабирования и эффектов
htmlacademy-javascript/2086233-kekstagram-simple-27 pull request #7
Opened 2022-11-03 08:46 UTC by Victoria273

Алёна, привет!
Не получается понять, почему у меня в масштабе NaN%, пробовала убирать шаблонную строку отсюда let newScaleValue = Number(scaleValue.value) - STEP; не помогает. 
Эффект не передается на .img-upload__preview, не появляется позунок на слайдере

2022-11-07 09:37 UTC, Safyann requested changes

2022-11-07 09:37 UTC, Safyann commented on js/scale-editing.js
> +  let newScaleValue = `${Number(scaleValue.value) - STEP}`;
scaleValue.value - число с %, то есть он строку не может преобразовать в число, надо тогда удалить все символы и оставить только числа, https://efim360.ru/javascript-kak-poluchit-tolko-czifry-iz-stroki/

2022-11-07 09:37 UTC, Safyann commented on js/form-popup.js
>  imgUpload.addEventListener('change', (evt) => {
так как evt нигде не используется в функции, то и передавать его не надо

2022-11-07 09:37 UTC, Safyann commented on js/form-popup.js
> +  uploadCancel.addEventListener('click', (evt) => {
так как evt нигде не используется в функции, то и передавать его не надо

2022-11-07 09:37 UTC, Safyann commented on js/form-popup.js
> +  uploadCancel.removeEventListener('click', (evt) => {
так как evt нигде не используется в функции, то и передавать его не надо

2022-11-07 09:37 UTC, Safyann commented on js/effect-editing.js
> +effectLevelSlider.noUiSlider.on('update', onSliderUpdate);
нет обработчика на  клик по эффектам, то есть функция никогда не срабатывает потому что считает что всегда один эффект, добавить обработчик на смену эффекта

2022-11-07 09:37 UTC, Safyann commented on js/effect-editing.js
> +  if (!evt.target.classList.contains('.effects__radio')) {
так как уже есть упоминание что это класс (classList), то тогда класс пишется без точки, то есть classList.contains("effects__radio")

2022-11-07 09:37 UTC, Safyann commented on js/effect-editing.js
> +  const sliderValue = effectLevelSlider.noUislider.get();
effectLevelSlider.noUislider.get() не сработает, так как есть опечатка в noUislider, slider с большой надо noUiSlider

2022-11-07 12:19 UTC, Victoria273 commented on js/effect-editing.js
> +effectLevelSlider.noUiSlider.on('update', onSliderUpdate);
Алёна, привет! Спасибо! Попыталась добавить обработчик на клик, но коллбэк не придумала какой передавать..Поменяла uploadEffectLevel на непосредственно форму imgUploadForm, всё заработало

2022-11-10 06:33 UTC, Safyann approved these changes
Принято, есть небольшая опечатка

2022-11-10 06:33 UTC, Safyann commented on js/scale-editing.js
> +  imgUploadPreview.style.transform = 'scale(sizePercent / 100)';
стала строка, scale просто не сработает, было `scale(${value / 100})`

2022-11-10 06:33 UTC, merged