Настраивает отправку и получение данных с сервера
htmlacademy-javascript/2086233-kekstagram-simple-27 pull request #8
Opened 2022-11-13 17:38 UTC by Victoria273

Алёна, привет!
Я запуталась, долго думала, не удалось понять как реализовать получение фото пользователей с сервера и при отправке поста на сервер не получился вывод сообщений для пользователя (из шаблонов) в случае успеха или ошибки при загрузке..Подскажи, пожалуйста

2022-11-15 16:44 UTC, Safyann requested changes

2022-11-15 16:44 UTC, Safyann commented on js/photos-generation.js
>  import {POSTS_COUNT, postsContent} from './data.js';
удаляем, так как не используем

2022-11-15 16:44 UTC, Safyann commented on js/photos-generation.js
> +import {getData} from './load.js';
получать лучше не тут, а в main

2022-11-15 16:44 UTC, Safyann commented on js/photos-generation.js
> +const loadPhotos = getData(console.log, console.error);
вынесем получение данных в main

2022-11-15 16:44 UTC, Safyann commented on js/photos-generation.js
> +  content.forEach((url, likes, comments) => {
тут декомпозируем переменную, поэтому не просто (url, likes, comments), а ({ url, likes, comments })

2022-11-15 16:44 UTC, Safyann commented on js/photos-generation.js
> +
лучше экспортировать генерацию export { generatePhotos };

2022-11-15 16:44 UTC, Safyann commented on js/main.js
>  import {postsContent} from './data.js';
не используем, удаляем

2022-11-15 16:44 UTC, Safyann commented on js/main.js
>  import './photos-generation.js';
добавляем import { getData } from "./load.js";
import { generatePhotos } from "./photos-generation.js";
import { showAlert } from "./utils.js";

2022-11-15 16:44 UTC, Safyann commented on js/main.js
>  console.log(postsContent);
уже не нужен, удаляем

2022-11-15 16:44 UTC, Safyann commented on js/main.js
добавляем получение данных 
getData(
  (photos) => generatePhotos(photos), // при успехе генерируем изображения
  showAlert // при ошибке показать уведомление
);

2022-11-15 16:44 UTC, Safyann commented on js/load.js
> +const getData = (onSuccess, onError) => () => fetch('https://27.javascript.pages.academy/kekstagram-simple/data')
() => лишнее, не проходит обработка события

2022-11-15 16:44 UTC, Safyann commented on js/utils.js
> +  const alertContainer = document.querySelector('.error__inner');
alertContainer будет null, так как его нет, такого класса в body, это класс для шаблона, можно alertContainer = document.querySelector("body");

2022-11-15 16:44 UTC, Safyann commented on js/utils.js
> +  const successMessageContainer = document.querySelector('.success__inner');
то же самое что с ошибкой

2022-11-15 16:44 UTC, Safyann commented on js/form-popup.js
> +  commentField.value = '';
дважды commentField.value = '';

2022-11-15 16:44 UTC, Safyann commented on js/comment-validation.js
> +};
действие и обработчик разделяют, то есть
`
const setUserFormSubmit = (evt) => {
  evt.preventDefault();
  const isValid = pristine.validate();
  if (isValid) {
    sendData(showSuccess, showAlert, new FormData(evt.target));
  }
};

selectImageForm.addEventListener("submit", setUserFormSubmit);
`

2022-11-15 16:44 UTC, Safyann commented on js/load.js
> +      showSuccess();
я бы убрала, так как можно вызвать в другом месте

2022-11-15 16:44 UTC, Safyann commented on js/comment-validation.js
> +import {showAlert} from './utils.js';
добавить showSuccess

2022-11-18 11:17 UTC, Victoria273 commented
Алёна, привет! Исправила ошибки, масштабирование работает и показывается ошибка при отправке данных на сервер. Всегда показывается только ошибка загрузки (нет showSuccess) и окно не закрывается, хотя написала .removeChild(), но на Esc реагирует сама форма (пробовала вешать обработчик на window). 
И пока не сообразила как-то иначе closeEditPhoto передать в setUserFomSubmit, чтобы сброс только при успешной загрузке или закрытии формы пользователем..

2022-11-18 18:26 UTC, Safyann requested changes
добавила комментов

2022-11-18 18:26 UTC, Safyann commented on js/main.js
> +setUserFormSubmit(closeEditPhoto);
изначально проверку делать не надо, так как нечего + нет event, можно удалить

2022-11-18 18:26 UTC, Safyann commented on js/utils.js
> +  const alertContainer = document.querySelector('body');
alertContainer и successMessageContainer - одно и тоже, можно вынести из функций
` 
const body = document.querySelector("body");
`

2022-11-18 18:26 UTC, Safyann commented on js/utils.js
> +      alertContainer.removeChild(fragment);
удалять надо не fragment, так как js не знает что это такое, надо удалять document.querySelector(".error") или .success в зависимости от того что показать

2022-11-18 18:26 UTC, Safyann commented on js/utils.js
> +  document.addEventListener('click', onSomeAreaClick);
добавить еще один прослушиватель событий  document.addEventListener("keydown", closeMessage);

2022-11-18 18:26 UTC, Safyann commented on js/utils.js
> +};
можно заметить что функции показа ошибки и успеха имеют одинаковый функционал, поэтому предлагаю не дулбировать код,  а оптимизировать

`
const showMessage = (status) => {
  const templateFragment = document.querySelector(`#${status}`).content;
  const template = templateFragment.querySelector(`.${status}`);
  ...

  const button = document.querySelector(`.${status}__button`);

  const onSomeAreaClick = (evt) => {
    if (evt.target.className !== `${status}__inner`) {
      body.removeChild(document.querySelector(`.${status}`));
     ...
    }
  };
  const closeMessage = () => {
    body.removeChild(document.querySelector(`.${status}`));
    ...
  };
  button.addEventListener("click", () => {
    closeMessage();
  });
  document.addEventListener("keydown", onPopupEscKeydown);
...
};
`
оставила чуть тебе подумать
ну и вызывать 

`
const showAlert = () => {
  showMessage("error");
};
`

2022-11-19 11:27 UTC, merged